# Generated by Django 3.1.1 on 2020-10-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='test_date',
            field=models.IntegerField(default=100),
        ),
    ]
