# Generated by Django 3.1.1 on 2020-10-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_test_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='test_date',
        ),
    ]
