# Generated by Django 3.1.1 on 2020-10-01 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_remove_destination_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='days',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=99999),
            preserve_default=False,
        ),
    ]
